import { createHash } from "node:crypto";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const repositoryRoot = dirname(dirname(fileURLToPath(import.meta.url)));
const stylesDirectory = join(repositoryRoot, "styles");
const bundledStylesPath = join(repositoryRoot, "styles.css");
const scriptPath = join(repositoryRoot, "script.js");
const htmlPath = join(repositoryRoot, "index.html");
const checkOnly = process.argv.includes("--check");
const extractStyles = process.argv.includes("--extract");

const styleParts = [
  "foundation.css",
  "hero.css",
  "work.css",
  "profile.css",
  "responsive.css",
  "modes.css",
];

const digest = (content) => createHash("sha256").update(content).digest("hex").slice(0, 10);

const replaceSingle = (content, pattern, replacement, label) => {
  const matches = content.match(new RegExp(pattern.source, pattern.flags.includes("g") ? pattern.flags : `${pattern.flags}g`));

  if (matches?.length !== 1) {
    throw new Error(`Expected one ${label} cache key in index.html, found ${matches?.length ?? 0}.`);
  }

  return content.replace(pattern, replacement);
};

const extractCurrentBundle = async () => {
  const currentBundle = await readFile(bundledStylesPath, "utf8");
  const markers = [
    { file: "foundation.css", marker: null },
    { file: "hero.css", marker: "\n.hero {\n" },
    { file: "work.css", marker: "\n.now {\n" },
    { file: "profile.css", marker: "\n.about {\n" },
    { file: "responsive.css", marker: "\n@media (max-width: 1180px) {\n" },
    { file: "modes.css", marker: "\n@media print {\n" },
  ];
  const boundaries = markers.map(({ marker }) => (marker === null ? 0 : currentBundle.indexOf(marker) + 1));

  if (boundaries.some((boundary) => boundary < 0) || new Set(boundaries).size !== boundaries.length) {
    throw new Error("Could not find every stable CSS section marker in styles.css.");
  }

  await mkdir(stylesDirectory, { recursive: true });

  await Promise.all(
    markers.map(async ({ file }, index) => {
      const end = boundaries[index + 1] ?? currentBundle.length;
      const section = currentBundle.slice(boundaries[index], end).trimEnd();
      await writeFile(join(stylesDirectory, file), `${section}\n`);
    }),
  );
};

if (extractStyles) {
  await extractCurrentBundle();
}

const styleSources = await Promise.all(
  styleParts.map(async (file) => ({
    file,
    content: (await readFile(join(stylesDirectory, file), "utf8")).trimEnd(),
  })),
);

const bundledStyles = `${[
  "/* Generated by scripts/build-assets.mjs. Edit files in styles/ instead. */",
  ...styleSources.map(({ file, content }) => `/* ${file} */\n${content}`),
].join("\n\n")}\n`;

const script = await readFile(scriptPath, "utf8");
const html = await readFile(htmlPath, "utf8");
const nextHtmlWithStyles = replaceSingle(
  html,
  /styles\.css\?v=[^"]+/,
  `styles.css?v=${digest(bundledStyles)}`,
  "stylesheet",
);
const nextHtml = replaceSingle(
  nextHtmlWithStyles,
  /script\.js\?v=[^"]+/,
  `script.js?v=${digest(script)}`,
  "script",
);

if (checkOnly) {
  const currentBundle = await readFile(bundledStylesPath, "utf8");
  const failures = [];

  if (currentBundle !== bundledStyles) failures.push("styles.css is not built from the files in styles/.");
  if (html !== nextHtml) failures.push("index.html contains stale CSS or JavaScript cache keys.");

  if (failures.length) {
    console.error("Generated assets are out of date:");
    failures.forEach((failure) => console.error(`- ${failure}`));
    console.error("Run `pnpm run build` and commit the generated files.");
    process.exitCode = 1;
  } else {
    console.log(`Generated assets are current: CSS ${digest(bundledStyles)}, JS ${digest(script)}.`);
  }
} else {
  await writeFile(bundledStylesPath, bundledStyles);
  if (html !== nextHtml) await writeFile(htmlPath, nextHtml);
  console.log(`Built styles.css and cache keys: CSS ${digest(bundledStyles)}, JS ${digest(script)}.`);
}
